table Date
	lineageTag: 4b285ac7-5bf6-4f06-96a6-915af13bd8fe

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6785a7ba-d6f8-4805-aea1-f63a402c5f6c
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Day Number'
		dataType: int64
		formatString: 0
		lineageTag: b9c33d3e-ce19-4f30-94c8-0f342242536b
		summarizeBy: none
		sourceColumn: Day Number

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: c35beae5-f639-439c-997b-57b3e1911a24
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 2426a69c-9a3c-4097-a78f-df091e991acc
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Short Month'
		dataType: string
		lineageTag: 87c348a4-fbe4-415e-af8d-526c0b801621
		summarizeBy: none
		sourceColumn: Short Month

		annotation SummarizationSetBy = Automatic

	column 'Calendar Month Number'
		dataType: int64
		formatString: 0
		lineageTag: a5b1f9ff-9eff-410d-a357-346d09642354
		summarizeBy: none
		sourceColumn: Calendar Month Number

		annotation SummarizationSetBy = Automatic

	column 'Calendar Month Label'
		dataType: string
		lineageTag: 86adad1a-d9d8-4587-9441-0ca9bb9516ba
		summarizeBy: none
		sourceColumn: Calendar Month Label

		annotation SummarizationSetBy = Automatic

	column 'Calendar Year'
		dataType: int64
		formatString: 0
		lineageTag: 9e7dcde0-91df-4ffa-8475-f5b3a365111e
		summarizeBy: none
		sourceColumn: Calendar Year

		annotation SummarizationSetBy = Automatic

	column 'Calendar Year Label'
		dataType: string
		lineageTag: 26497b0b-1b3c-4738-aa87-9e23e9bddfdb
		summarizeBy: none
		sourceColumn: Calendar Year Label

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 867ce374-450f-4a42-90a9-d7bb2d55ca32
		summarizeBy: none
		sourceColumn: Fiscal Month Number

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month Label'
		dataType: string
		lineageTag: 13ee91a0-f550-4e0f-8136-2d0b63d0f459
		summarizeBy: none
		sourceColumn: Fiscal Month Label

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: e24234a2-d2d4-45f0-ae16-9d351417c063
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Label'
		dataType: string
		lineageTag: 97af4818-cb67-4f3c-9cbc-a0c9034514ff
		summarizeBy: none
		sourceColumn: Fiscal Year Label

		annotation SummarizationSetBy = Automatic

	column 'ISO Week Number'
		dataType: int64
		formatString: 0
		lineageTag: 6719c836-53a5-4745-a6d3-3e91fc8eb587
		summarizeBy: none
		sourceColumn: ISO Week Number

		annotation SummarizationSetBy = Automatic

	partition Date = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents(FilePath&DateTable), [Delimiter = ",", Columns = 14, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Date", type date}, {"Day Number", Int64.Type}, {"Day", Int64.Type}, {"Month", type text}, {"Short Month", type text}, {"Calendar Month Number", Int64.Type}, {"Calendar Month Label", type text}, {"Calendar Year", Int64.Type}, {"Calendar Year Label", type text}, {"Fiscal Month Number", Int64.Type}, {"Fiscal Month Label", type text}, {"Fiscal Year", Int64.Type}, {"Fiscal Year Label", type text}, {"ISO Week Number", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

